language: generic
before_deploy: 
  - rm README.md
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "codehunt"
  skip_cleanup: true
  region: "us-east-1"
  on:
    branch: master
